
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    ports:
      - "5000:5000"
    networks:
      - app-network

  log-processor:
    image: busybox
    command: sh -c "tail -f /logs/app.log"
    volumes:
      - ./logs:/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
